# Site settings
title: OpenDoor
email: moyer.will@gmail.com
description: "Welcome to OpenDoor"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: /blog/:title
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]