# Site settings
title: Horizon
email: moyer.will@gmail.com
description: "Welcome to Horizon"
baseurl: ""
url: "http://horizonapp.co"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]